export const fields: string[] = [
  'accessibilityOptions',
  'allowsDogs',
  'businessStatus',
  'openingHours',
  'hasCurbsidePickup',
  'hasDelivery',
  'hasDineIn',
  'isGoodForGroups',
  'isGoodForChildren',
  'displayName',
  'location',
  'priceLevel',
  'editorialSummary',
];

export const includedType: string[] = [
  'restaurant',
  'bar',
  'bakery',
  'cafe',
  'country',
  'park',
  'zoo',
  'night_club',
  'tourist_attraction',
  'hotel',
  'lodging',
  'campground',
  'motel',
  'resort_hotel',
  'beach',
  'airport',
  'point_of_interest',
  'food',
  'landmark',
];
